### ISSUE TITLE
Joel, code responsibility 

### ISSUE THREAD

**Issue by MadeWithPaper** [MadeWithPaper/Simternship#46]
Leader board
resume
player

**Comment by joeldentici** [comment]
Edited original comment: added "player"

**Comment by joeldentici** [comment]
Need to discuss the interface of Player class a bit more. It is pretty central to the rest of the application, so we need to figure out what its concerns exactly are.

We will probably also want to introduce a Game class to hold the game state, and an Application class to hold the overall application state (not just state of a game). The Game class can coordinate between Player and Career Fair and Player and Prep Session.

**Comment by MadeWithPaper** [comment]
done and closed
